version: '3.9'

services:
  db:
    image: postgres:latest
    volumes:
    - db:/var/lib/postgresql/data
    restart: always
    environment:
    - POSTGRES_DB=wordpress
    - POSTGRES_USER=wordpress
    - POSTGRES_PASSWORD=wordpress
    networks:
    - wordpress

  wordpress:
    depends_on:
    - db
    image: wordpress:latest
    ports:
    - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:5432
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
    - wordpress

volumes:
  db: {}

networks:
  wordpress: {}

